server:
  port: 9211
  servlet:
    context-path: /association
spring:
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/association?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://192.168.231.132:3306/association?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxWait: 60000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl